org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
SUPABASE_URL=https://jqhspzyhdrusdrzoffbw.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxaHNwenloZHJ1c2Ryem9mZmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0Njg5MzQsImV4cCI6MjEwMTA0NDkzNH0.a1G7PpsHYJOMFR8NMXsAk72MQ5uXKzO-gaqXqCqceEg

